//
// Created by shach on 02/11/2021.
//

#ifndef ANOMALY_DETECTION_UTIL_CPP_TIMESERIES_H
#define ANOMALY_DETECTION_UTIL_CPP_TIMESERIES_H


class TimeSeries {

};


#endif //ANOMALY_DETECTION_UTIL_CPP_TIMESERIES_H
